Forms - Smart/Controllers/PersonasController.cs
using Forms___Smart.Models.ModelsWeb;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Forms___Smart.Controllers
{
    public class PersonasController : Controller
    {
        // GET: Personas
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Crear_personas()
        {
            object retuly = Session["token"];
            string API_KEY = Convert.ToString(retuly);

            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri(ConfigurationManager.AppSettings["URL_SERVER"].ToString());
            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/x-www-form-urlencoded"));
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", API_KEY);

            var result = client.GetAsync("PEOPLE/GET_DATA_PEOPLE").Result.Content.ReadAsStringAsync().Result;
            if (result != null)
            {
                GetDataPeopleViewModels listProductos = JsonConvert.DeserializeObject<GetDataPeopleViewModels>(result);
                if (listProductos != null && listProductos.Type == "Success")
                {
                    return View(listProductos);
                }
                else
                {
                    return RedirectToAction("index", "Error404");
                }
            }
            else
            {
                return RedirectToAction("index", "Error404");
            }
        }

        [HttpPost]
        public ActionResult Crear_personas(ObjCrearPersonas data)
        {
            object retuly = Session["token"];
            string API_KEY = Convert.ToString(retuly);

            IEnumerable<KeyValuePair<string, string>> Parametros = new List<KeyValuePair<string, string>>()
            {
                new KeyValuePair<string, string>("id_type_id",Convert.ToString(data.id_type_id)),
                new KeyValuePair<string, string>("identifications",Convert.ToString(data.identifications)),
                new KeyValuePair<string, string>("id_city",Convert.ToString(data.id_city)),
                new KeyValuePair<string, string>("id_gender",Convert.ToString(data.id_gender)),
                new KeyValuePair<string, string>("id_profile",Convert.ToString(data.id_profile)),
                new KeyValuePair<string, string>("names",Convert.ToString(data.names)),
                new KeyValuePair<string, string>("surnames",Convert.ToString(data.surnames)),
                new KeyValuePair<string, string>("password",Convert.ToString(data.password)),
                new KeyValuePair<string, string>("confirPassword",Convert.ToString(data.confirPassword)),
                new KeyValuePair<string, string>("usuario",Convert.ToString(data.usuario)),
                new KeyValuePair<string, string>("email",Convert.ToString(data.email)),
                new KeyValuePair<string, string>("phone",Convert.ToString(data.phone))
            };
            HttpContent Objet = new FormUrlEncodedContent(Parametros);

            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri(ConfigurationManager.AppSettings["URL_SERVER"].ToString());
            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/x-www-form-urlencoded"));
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", API_KEY);

            var result = client.PostAsync("PEOPLE/POST_CREATE_PEOPLE", Objet).Result.Content.ReadAsStringAsync().Result;
            if (result != null)
            {
                GetTypeResultViewModels listProductos = JsonConvert.DeserializeObject<GetTypeResultViewModels>(result);
                if (listProductos != null && listProductos.Type == "Success")
                {
                    return Json(listProductos);
                }
                else
                {
                    return Json(listProductos);
                }
            }
            else
            {
                return RedirectToAction("index", "Error404");
            }
        }

        public ActionResult Editar_personas(int id)
        {
            return View();
        }
    }
}

Forms - Smart/Views/Personas/Crear_personas.cshtml
@model Forms___Smart.Models.ModelsWeb.GetDataPeopleViewModels
@{
    if (Session["id_users"] == null)
    {
        Response.Redirect("~/Sign_in/Index");
    }
}

</br>
</br>
<div class="single-pro-review-area mt-t-30 mg-b-15">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="product-payment-inner-st">
                    <ul id="myTabedu1" class="tab-review-design">
                        <li class="active"><a href="#description">Informacion Basica</a></li>
                    </ul>
                    <div id="myTabContent" class="tab-content custom-product-edit">
                        <div class="product-tab-list tab-pane fade active in" id="description">
                            <div class="row">
                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                    <div class="review-content-section">
                                        <div id="dropzone1" class="pro-ad">
                                            <form action="/upload" class="dropzone dropzone-custom needsclick add-professors" id="demo1-upload">
                                                <div class="row">
                                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                                        <div class="form-group">
                                                            @Html.DropDownListFor(model => model.id_type_id, new SelectList(Model.ListTipoId, "id", "valor"), "Seleccione Tipo identificación", new { @class = "form-control", required = "required" })
                                                        </div>
                                                        <div class="form-group">
                                                            @Html.TextBoxFor(model => model.identifications, new { @class = "form-control", placeholder = "Identificación", type = "number", required = "required" })
                                                        </div>
                                                        <div class="form-group">
                                                            @Html.TextBoxFor(model => model.names, new { @class = "form-control", placeholder = "Nombres", type = "text", required = "required" })
                                                        </div>
                                                        <div class="form-group">
                                                            @Html.TextBoxFor(model => model.surnames, new { @class = "form-control", placeholder = "Apellidos", type = "text", required = "required" })
                                                        </div>
                                                        <div class="form-group">
                                                            @Html.TextBoxFor(model => model.phone, new { @class = "form-control", placeholder = "Telefono", type = "number", required = "required" })
                                                        </div>
                                                        <div class="form-group">
                                                            @Html.TextBoxFor(model => model.email, new { @class = "form-control", placeholder = "Correo", type = "email", required = "required" })
                                                        </div>
                                                    </div>
                                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                                        <div class="form-group">
                                                            @Html.DropDownListFor(model => model.id_city, new SelectList(Model.ListGender, "id", "valor"), "Seleccione una ciudad", new { @class = "form-control", required = "required" })
                                                        </div>
                                                        <div class="form-group">
                                                            @Html.DropDownListFor(model => model.id_gender, new SelectList(Model.ListCity, "id", "valor"), "Seleccione un genero", new { @class = "form-control", required = "required" })
                                                        </div>
                                                        <div class="form-group">
                                                            @Html.DropDownListFor(model => model.id_profile, new SelectList(Model.ListProfile, "id", "valor"), "Seleccione un perfil", new { @class = "form-control", required = "required" })
                                                        </div>
                                                        <div class="form-group">
                                                            @Html.TextBoxFor(model => model.usuario, new { @class = "form-control", placeholder = "Usuario", type = "text", required = "required" })
                                                        </div>
                                                        <div class="form-group">
                                                            @Html.TextBoxFor(model => model.password, new { @class = "form-control", placeholder = "Contraseña", type = "password", required = "required" })
                                                        </div>
                                                        <div class="form-group">
                                                            @Html.TextBoxFor(model => model.confirPassword, new { @class = "form-control", placeholder = "Confirmar contraseña", type = "password", required = "required" })
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="row">
                                                    <div class="col-lg-12">
                                                        <div class="payment-adress">
                                                            <button type="button" id="guardar" class="btn btn-primary waves-effect waves-light">Submit</button>
                                                        </div>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script>

    $(document).ready(function () {    
        $("#guardar").click(function () {
            var data = {
                id_type_id: $("#id_type_id").val(),
                id_gender: $("#id_gender").val(),
                id_profile: $("#id_profile").val(),
                identifications: $("#identifications").val(),
                id_city: $("#id_city").val(),
                names: $("#names").val(),
                surnames: $("#surnames").val(),
                email: $("#email").val(),
                phone: $("#phone").val(),
                usuario: $("#usuario").val(),
                password: $("#password").val(),
                confirPassword: $("#confirPassword").val()
            };
            if (data.id_type_id != "") {
                if (data.identifications != "") {
                    if (data.names != "") {
                        if (data.surnames != "") {
                            if (data.phone != "") {
                                if (data.email != "") {
                                    if (data.id_city != "") {
                                         if (data.id_gender != "") {
                                             if (data.id_profile != "") {
                                                 if (data.usuario != "") {
                                                     if (data.password == data.confirPassword) {
                                                            $.ajax({
                                                                type: "POST",
                                                                url: '@Url.Action("Crear_personas", "Personas")',
                                                                cache: true,
                                                                async: false,
                                                                data: JSON.stringify({ data: data }),
                                                                contentType: "application/json; charset=utf-8",
                                                                success: function (resultado) {
                                                                    console.log(resultado);
                                                                },
                                                                error: function (result) {
                                                                    console.log(result);
                                                                }
                                                            });
                                                     } else {
                                                        $("#confirPassword").focus();
                                                     }
                                                 } else {
                                                    $("#usuario").focus();
                                                 }  
                                             } else {
                                                $("#id_profile").focus();
                                             }  
                                         } else {
                                            $("#id_gender").focus();
                                         }  
                                     } else {
                                        $("#id_city").focus();
                                     }  
                                } else {
                                    $("#email").focus();
                                }  
                            } else {
                                $("#phone").focus();
                            }  
                        } else {
                            $("#surnames").focus();
                        }                  
                    } else {
                        $("#names").focus();
                    }                   
                } else {
                    $("#identifications").focus();
                }                
            } else {
                $("#id_type_id").focus();
            }
        });
    });
</script>

Forms - Smart/Views/Personas/Editar_personas.cshtml
@{
    ViewBag.Title = "Editar_personas";
}

<h2>Editar_personas</h2>

Forms - Smart/Views/Personas/Index.cshtml
@{
    if (Session["id_users"] == null)
    {
        Response.Redirect("~/Sign_in/Index");
    }
}
</br>
</br>
<div class="data-table-area mg-b-15 mt-30">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="sparkline13-list">
                    <div class="sparkline13-hd">
                        <div class="main-sparkline13-hd">
                            <h1>Personas</h1>
                        </div>
                    </div>
                    <div class="sparkline13-graph">
                        <div class="datatable-dashv1-list custom-datatable-overright">
                            <div class="datatable-ct">
                                <a class="fa fa-plus" href="@Url.Action("Crear_personas", "Personas")"></a>
                            </div>
                            <div id="toolbar">
                                <select class="form-control dt-tb">
                                    <option value="">Seleccione cargo</option>
                                    <option value="all">Export All</option>
                                    <option value="selected">Export Selected</option>
                                </select>
                            </div>
                            <div class="date-picker-inner">
                                <div class="form-group data-custon-pick" id="data_1">
                                    <label>Fecha Inicio</label>
                                    <div class="input-group date">
                                        <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                        <input type="text" class="form-control" value="10/04/2017">
                                    </div>
                                </div>
                            </div>
                            <table id="table" data-toggle="table" data-pagination="true" data-search="true" data-show-columns="true" data-show-pagination-switch="true" data-show-refresh="true" data-key-events="true" data-show-toggle="true" data-resizable="true" data-cookie="true"
                                   data-cookie-id-table="saveId" data-show-export="true" data-click-to-select="true" data-toolbar="#toolbar">
                                <thead>
                                    <tr>
                                        <th data-field="state" data-checkbox="true"></th>
                                        <th data-field="id">ID</th>
                                        <th data-field="Nombre">Nombre</th>
                                        <th data-field="Identificacion">Identificacion</th>
                                        <th data-field="Telefono">Telefono</th>
                                        <th data-field="Correo">Correo</th>
                                        <th data-field="Cargo">Cargo</th>
                                        <th data-field="Usuario">Usuario</th>
                                        <th data-field="fecha_creacion">Fecha Sistema</th>
                                        <th data-field="Acciones">Acciones</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td></td>
                                        <td>1</td>
                                        <td>Super Admin</td>
                                        <td>CC: 104500000</td>
                                        <td>+57 3013723158</td>
                                        <td>superadmin@gmail.com</td>
                                        <td>SuperAdministrador</td>
                                        <td>SuperAdmin</td>
                                        <td>2020-04-10</td>
                                        <td class="datatable-ct">
                                            <a class="fa fa-check" href="@Url.Action("Index", "Home")"></a>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td>1</td>
                                        <td>Super Admin</td>
                                        <td>CC: 104500000</td>
                                        <td>+57 3013723158</td>
                                        <td>superadmin@gmail.com</td>
                                        <td>SuperAdministrador</td>
                                        <td>SuperAdmin</td>
                                        <td>2020-04-10</td>
                                        <td class="datatable-ct">
                                            <i class="fa fa-check"></i>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td>1</td>
                                        <td>Super Admin</td>
                                        <td>CC: 104500000</td>
                                        <td>+57 3013723158</td>
                                        <td>superadmin@gmail.com</td>
                                        <td>SuperAdministrador</td>
                                        <td>SuperAdmin</td>
                                        <td>2020-04-10</td>
                                        <td class="datatable-ct">
                                            <i class="fa fa-check"></i>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td>1</td>
                                        <td>Super Admin</td>
                                        <td>CC: 104500000</td>
                                        <td>+57 3013723158</td>
                                        <td>superadmin@gmail.com</td>
                                        <td>SuperAdministrador</td>
                                        <td>SuperAdmin</td>
                                        <td>2020-04-10</td>
                                        <td class="datatable-ct">
                                            <i class="fa fa-check"></i>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td>1</td>
                                        <td>Super Admin</td>
                                        <td>CC: 104500000</td>
                                        <td>+57 3013723158</td>
                                        <td>superadmin@gmail.com</td>
                                        <td>SuperAdministrador</td>
                                        <td>SuperAdmin</td>
                                        <td>2020-04-10</td>
                                        <td class="datatable-ct">
                                            <i class="fa fa-check"></i>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td>1</td>
                                        <td>Super Admin</td>
                                        <td>CC: 104500000</td>
                                        <td>+57 3013723158</td>
                                        <td>superadmin@gmail.com</td>
                                        <td>SuperAdministrador</td>
                                        <td>SuperAdmin</td>
                                        <td>2020-04-10</td>
                                        <td class="datatable-ct">
                                            <i class="fa fa-check"></i>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        </div>
                </div>
            </div>
        </div>
    </div>
</div>