Forms - Smart/Controllers/Sign_inController.cs
using Forms___Smart.Models.ModelsWeb;
using Newtonsoft.Json;
using System;
using System.Configuration;
using System.IdentityModel.Tokens.Jwt;
using System.IO;
using System.Net;
using System.Web.Mvc;

namespace Forms___Smart.Controllers
{
    public class Sign_inController : Controller
    {
        public ActionResult Index()
        {
            string _token = Convert.ToString(Session["token"]);           

            if (_token != "")
            {   
                var handler = new JwtSecurityTokenHandler();
                var token = handler.ReadJwtToken(_token);
                if (token != null)
                {
                    DateTime fecha = DateTime.Now;
                    var foreachs = token.Claims;
                    foreach (var item in foreachs)
                    {
                        if (item.Type == "exp")
                        {
                            System.DateTime dtDateTime = new DateTime(1970, 1, 1, 0, 0, 0, 0, System.DateTimeKind.Utc);
                            dtDateTime = dtDateTime.AddSeconds(Convert.ToDouble(item.Value)).ToLocalTime();
                            fecha = dtDateTime;
                        }
                    }

                    if (DateTime.Now < fecha)
                    {
                        return RedirectToAction("index", "Home");
                    }
                    else
                    {
                        Session["token"] = null;
                        Session["id_users"] = null;

                        return View();
                    }
                }
                else
                {
                    Session["token"] = null;
                    Session["id_users"] = null;

                    return View();
                }
            }
            else
            {
                Session["token"] = null;
                Session["id_users"] = null;
                return View();
            }
        }

        [HttpPost]
        public ActionResult ValidarCredenciales(LoginRequestViewModels userlogin, FormCollection form)
        {            
            var httpWebRequest = (HttpWebRequest)WebRequest.Create(ConfigurationManager.AppSettings["URL_SERVER"].ToString() + "LOGIN/AUTHENTICATE");
            httpWebRequest.ContentType = "application/json";
            httpWebRequest.Method = "POST";

            using (var streamWriter = new StreamWriter(httpWebRequest.GetRequestStream()))
            {
                string json =   "{\"username\":\"" + userlogin.username + "\"," + "\"password\":\"" + userlogin.password + "\"}";
                streamWriter.Write(json);
                streamWriter.Close();
            }

            var httpResponse = (HttpWebResponse)httpWebRequest.GetResponse();
            using (var streamReader = new StreamReader(httpResponse.GetResponseStream()))
            {
                var result = streamReader.ReadToEnd();
                httpResponse.Close();
                streamReader.Close();

                if (result != null)
                {
                    LoginResultViewModels listProductos = JsonConvert.DeserializeObject<LoginResultViewModels>(result);
                    if (listProductos.status == "Error" || listProductos.Tipo == "Error")
                    {
                        userlogin.message = listProductos.Descripcion;
                        return View("Index", userlogin);
                    }
                    else
                    {
                        Session["id_users"] = listProductos.id_users;
                        Session["id_perfil"] = listProductos.id_perfil;
                        Session["id_status"] = listProductos.id_status;
                        Session["nombre"] = listProductos.nombre;
                        Session["username"] = listProductos.username;
                        Session["token"] = listProductos.token;

                        return RedirectToAction("index", "Home");
                    }                    
                }
                else
                {
                    userlogin.message = "Contraseña incorrecta";
                    return View("Index", userlogin);
                }
            }
        }
    }
}

Forms - Smart/Views/Sign_in/Index.cshtml
@model Forms___Smart.Models.ModelsWeb.LoginRequestViewModels
@{
    Layout = null;
}

<!doctype html>
<html class="no-js" lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Login - Quirón Virtual</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/x-icon" href="~/Content/img/favicon.ico">
    <link href="https://fonts.googleapis.com/css?family=Play:400,700" rel="stylesheet" />

    <link rel="stylesheet" href="~/Content/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/Content/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/Content/css/owl.carousel.css">
    <link rel="stylesheet" href="~/Content/css/owl.theme.css">
    <link rel="stylesheet" href="~/Content/css/owl.transitions.css">
    <link rel="stylesheet" href="~/Content/css/animate.css">
    <link rel="stylesheet" href="~/Content/css/normalize.css">
    <link rel="stylesheet" href="~/Content/css/main.css">
    <link rel="stylesheet" href="~/Content/css/morrisjs/morris.css">
    <link rel="stylesheet" href="~/Content/css/scrollbar/jquery.mCustomScrollbar.min.css">
    <link rel="stylesheet" href="~/Content/css/metisMenu/metisMenu.min.css">
    <link rel="stylesheet" href="~/Content/css/metisMenu/metisMenu-vertical.css">
    <link rel="stylesheet" href="~/Content/css/calendar/fullcalendar.min.css">
    <link rel="stylesheet" href="~/Content/css/calendar/fullcalendar.print.min.css">
    <link rel="stylesheet" href="~/Content/css/form/all-type-forms.css">
    <link rel="stylesheet" href="~/Content/style.css">
    <link rel="stylesheet" href="~/Content/css/responsive.css">
    <script src="~/Content/js/vendor/modernizr-2.8.3.min.js"></script>
</head>
<body>
    <div class="error-pagewrap">
        <div class="error-page-int">
            <div class="text-center m-b-md custom-login">
                <h3>QUIRÓN</h3>
                @*<p>Inicia Sesion</p>*@
            </div>
            <div class="content-error">
                <div class="hpanel">
                    <div class="panel-body">
                        @using (Html.BeginForm("ValidarCredenciales", "Sign_in", FormMethod.Post))
                        {
                            <form action="#" id="loginForm">
                                <div class="form-group">
                                    <label class="control-label" for="username">Username</label>
                                    @Html.TextBoxFor(model => model.username, new { @class = "form-control", placeholder = "Usuario", required = "required" })
                                </div>
                                <div class="form-group">
                                    <label class="control-label" for="password">Password</label>
                                    @Html.PasswordFor(model => model.password, new { @class = "form-control", placeholder = "Contraseña", required = "required" })
                                </div>
                                <button class="btn btn-success btn-block loginbtn">Sign In</button>

                                <br />
                                <div id="messagealert" class="alert alert-warning" role="alert">
                                    <span id="spanmessagealert">@Html.DisplayFor(model => model.message)</span>
                                </div>
                                <br />
                            </form>
                        }
                    </div>
                </div>
            </div>
            <div class="text-center login-footer">
                <p>Copyright © 2020. <a href="">Wemi</a></p>
            </div>
        </div>
    </div>

    <script src="~/Content/js/vendor/jquery-1.12.4.min.js"></script>
    <script src="~/Content/js/bootstrap.min.js"></script>
    <script src="~/Content/js/wow.min.js"></script>
    <script src="~/Content/js/jquery-price-slider.js"></script>
    <script src="~/Content/js/jquery.meanmenu.js"></script>
    <script src="~/Content/js/owl.carousel.min.js"></script>
    <script src="~/Content/js/jquery.sticky.js"></script>
    <script src="~/Content/js/jquery.scrollUp.min.js"></script>
    <script src="~/Content/js/scrollbar/jquery.mCustomScrollbar.concat.min.js"></script>
    <script src="~/Content/js/scrollbar/mCustomScrollbar-active.js"></script>
    <script src="~/Content/js/metisMenu/metisMenu.min.js"></script>
    <script src="~/Content/js/metisMenu/metisMenu-active.js"></script>
    <script src="~/Content/js/tab.js"></script>
    <script src="~/Content/js/icheck/icheck.min.js"></script>
    <script src="~/Content/js/icheck/icheck-active.js"></script>
    <script src="~/Content/js/plugins.js"></script>
    <script src="~/Content/js/main.js"></script>

    <script type="text/javascript">
        if ($("#spanmessagealert").text() != "") {
            $("#messagealert").css("display", "block");
        } else { $("#messagealert").css("display", "none"); }
    </script>
</body>
</html>